### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by kianjh** [Lgmrszd/CreateMountedStorages#3]
### Describe your issue

an error during common_setup event phase
java.lang.NoSuchFieldError: item_trash_can_tile
[latest.log](https://github.com/Lgmrszd/CreateMountedStorages/files/10362340/latest.log)
[crash-2023-01-06_18.35.22-fml.txt](https://github.com/Lgmrszd/CreateMountedStorages/files/10362343/crash-2023-01-06_18.35.22-fml.txt)

### Mod version

latest

### Forge version

40.1.76

### Create version

latest

**Comment by Lgmrszd** [comment]
Seems to be duplicate of #2, please refer to this one for updates on fix.
